### ISSUE TITLE
报告一个启动报错

### ISSUE THREAD

**Issue by chrysanthemum** [wind-framework/example#1]
/usr/local/Cellar/php/8.1.10_1/bin/php /Users/andy/project/t/example/start.php start
ValueError: Options should have the form ["wrappername"]["optionname"] = $value in /Users/andy/project/t/example/vendor/workerman/workerman/Worker.php:2311
Stack trace:
#0 /Users/andy/project/t/example/vendor/workerman/workerman/Worker.php(2311): stream_context_create()
#1 /Users/andy/project/t/example/vendor/wind-framework/web/src/HttpServer.php(57): Workerman\Worker->__construct()
#2 /Users/andy/project/t/example/vendor/wind-framework/wind-framework/src/base/Application.php(202): Wind\Web\HttpServer->__construct()
#3 /Users/andy/project/t/example/vendor/wind-framework/wind-framework/src/base/Application.php(72): Wind\Base\Application->runServers()
#4 /Users/andy/project/t/example/start.php(18): Wind\Base\Application::start()

**Comment by xpader** [comment]
example 的 config/server.php 有改动吗？如果有改动麻烦贴一下吧。
这种错误理论上是 context_options 参数设置有误，需要参照 https://www.php.net/manual/en/function.stream-context-create 这里进行配置。

**Comment by chrysanthemum** [comment]
config/server.php没有修改，源码原封不动的运行的，请再帮忙分析下了原因了。
需要提供说明请说明，这个项目很有创造性，希望能有很好的发展

**Comment by chrysanthemum** [comment]
如果把wind-framework/wind-framework/src/base/Application.php文件的第202行，
$worker = new $supportServers[$srv['type']]($srv['listen'], $srv);
中的 $srv 删掉，可以跑起来，然后包如下错误。


/usr/local/Cellar/php/8.1.10_1/bin/php /Users/andy/project/t/example/start.php start
Workerman[/Users/andy/project/t/example/start.php] start in DEBUG mode
------------------------------------------------------ WORKERMAN ------------------------------------------------------
Workerman version:4.1.8          PHP version:8.1.10           Event-Loop:Wind\Base\Amp
------------------------------------------------------- WORKERS -------------------------------------------------------
proto   user            worker                         listen                            processes    status           
unix    andy            ChannelServer                  unix:///tmp/wind-b2257772.sock    1             [OK]            
tcp     andy            HttpServer                     http://0.0.0.0:2346               2             [OK]            
tcp     andy            WebSocketServer                websocket://0.0.0.0:2347          1             [OK]            
tcp     andy            App\Process\MyMergedProcess    none                              1             [OK]            
tcp     andy            QueueConsumer.default          none                              2             [OK]            
tcp     andy            TaskWorker                     none                              2             [OK]            
-----------------------------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
[2023-03-09 08:41:11] access.INFO: 127.0.0.1 - - "GET / HTTP/1.1" 200 20 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" [] []
[2023-03-09 08:41:11] access.INFO: 127.0.0.1 - - "GET /favicon.ico HTTP/1.1" 200 0 "http://0.0.0.0:2346/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" [] []
[2023-03-09 08:41:11] SystemError.ERROR: Workerman\Redis\Exception: Workerman Redis Connection to redis://192.168.4.2:6379 timeout (5 seconds) in /Users/andy/project/t/example/vendor/wind-framework/redis/src/Redis.php:268
Stack trace:
#0 [internal function]: Wind\Redis\Redis->Wind\Redis\{closure}()
#1 /Users/andy/project/t/example/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#2 /Users/andy/project/t/example/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#3 /Users/andy/project/t/example/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#4 /Users/andy/project/t/example/vendor/workerman/redis/src/Client.php(445): Amp\{closure}()
 [] []
[2023-03-09 08:41:11] SystemError.ERROR: Workerman\Redis\Exception: Workerman Redis Connection to redis://192.168.4.2:6379 timeout (5 seconds) in /Users/andy/project/t/example/vendor/wind-framework/redis/src/Redis.php:268

**Comment by chrysanthemum** [comment]
xdebug到 workerman/workerman/Worker.php 的第2311行，
$this->_context = \stream_context_create($context_option);

$context_option 的值为如下：

array (
  'type' => 'http',
  'listen' => '0.0.0.0:2346',
  'worker_num' => 2,
  'reuse_port' => false,
  'socket' => 
  array (
    'backlog' => 102400,
  ),
)

**Comment by chrysanthemum** [comment]
<?php

$context_option1 = array (
    'type' => 'http',
    'listen' => '0.0.0.0:2346',
    'worker_num' => 2,
    'reuse_port' => false,
    'socket' =>
        array (
            'backlog' => 102400,
        ),
);

$t = \stream_context_create($context_option1);

print_r($t);
报错！

**Comment by chrysanthemum** [comment]
这样不报错
<?php

$context_option = array (
    'ser' => [
        'type' => 'http',
        'listen' => '0.0.0.0:2346',
        'worker_num' => 2,
        'reuse_port' => false,
    ],
    'socket' =>
        array (
            'backlog' => 102400,
        ),
);



$t = \stream_context_create($context_option);

print_r($t);

**Comment by chrysanthemum** [comment]
这样不报错
```
<?php

$context_option = array (
    'ser' => [
        'type' => 'http',
        'listen' => '0.0.0.0:2346',
        'worker_num' => 2,
        'reuse_port' => false,
    ],
    'socket' =>
        array (
            'backlog' => 102400,
        ),
);



$t = \stream_context_create($context_option);

print_r($t);




```

**Comment by chrysanthemum** [comment]
这样报错
```
<?php

$context_option = array (
    'type' => 'http',
    'listen' => '0.0.0.0:2346',
    'worker_num' => 2,
    'reuse_port' => false,
    'socket' =>
        array (
            'backlog' => 102400,
        ),
);



$t = \stream_context_create($context_option);

print_r($t);



```

**Comment by chrysanthemum** [comment]
貌似修改 wind-framework/wind-framework/src/base/Application.php文件的第202行的,

$worker = new $supportServers[$srv['type']]($srv['listen'], $srv);

中的$srv 参数结构可以修复这个问题

**Comment by chrysanthemum** [comment]
$worker = new $supportServers[$srv['type']]($srv['listen'], $srv);

去掉 $srv 参数配置对相关IP，一切正常，但是不知道会不会有什么影响~

**Comment by xpader** [comment]
你的原因应该是因为 wind-framework/web 这个组件是上一个版本 0.2.x 导致的，目前 HttpServer 和 WebSocketServer 这两个参数的 context_options 传递方式已经发生了改变，不再直接使用 server.php 里的第一层值。

目前 0.x 的版本间依赖有些问题，你可以在 example 的 composer.json 中将 wind-framework 相关的版本号前面的 ^ 符号全部改为 ~ 符号后，再使用 composer update 'wind-framework/*' 更新一遍再试。

现在的版本主要基于 yield 使用难度较大，后续的重点还是基于 php8.1 的无 yield/call 版本。

**Comment by chrysanthemum** [comment]
> 你的原因应该是因为 wind-framework/web 这个组件是上一个版本 0.2.x 导致的，目前 HttpServer 和 WebSocketServer 这两个参数的 context_options 传递方式已经发生了改变，不再直接使用 server.php 里的第一层值。
> 
> 目前 0.x 的版本间依赖有些问题，你可以在 example 的 composer.json 中将 wind-framework 相关的版本号前面的 ^ 符号全部改为 ~ 符号后，再使用 composer update 'wind-framework/*' 更新一遍再试。
> 
> 现在的版本主要基于 yield 使用难度较大，后续的重点还是基于 php8.1 的无 yield/call 版本。

万事开头难，看好这个项目，期待后续版本
